import type { FeedItem, Interest, LearningContent, Post, Profile } from "@/lib/types";

export const topicOptions = [
  "AI",
  "Business",
  "Finance",
  "Fitness",
  "Science",
  "Technology",
  "Fashion",
  "Music",
  "Entrepreneurship",
  "Other",
] as const satisfies readonly Interest[];

export const interestOptions = topicOptions;

export const goalOptions = ["Learn consistently", "Build better habits", "Track progress"] as const;

export const localProfiles: Profile[] = [
  {
    id: "local-learner",
    username: "learner",
    full_name: "VShare learner",
    headline: "Building a sharper daily learning rhythm",
    avatar_url: null,
    interests: ["AI", "Business", "Technology"],
    created_at: "2026-06-10T12:00:00.000Z",
    updated_at: "2026-06-10T12:00:00.000Z",
  },
];

export const learningContent: LearningContent[] = [
  {
    id: "ai-agent-basics",
    title: "How AI agents break tasks into decisions",
    summary: "A clear walkthrough of goals, tools, memory, and feedback loops inside useful agent workflows.",
    interests: ["AI", "Technology"],
    format: "article",
    durationMinutes: 8,
    level: "starter",
    createdAt: "2026-06-20T08:00:00.000Z",
    sourceLabel: "AI systems",
    media: { kind: "text", status: "available" },
  },
  {
    id: "ai-prompt-debugging",
    title: "Debug prompts by changing one variable at a time",
    summary: "A practical routine for isolating instruction, context, and output-format failures.",
    interests: ["AI"],
    format: "challenge",
    durationMinutes: 12,
    level: "intermediate",
    createdAt: "2026-06-19T08:00:00.000Z",
    sourceLabel: "Prompt practice",
    media: { kind: "video", status: "planned" },
  },
  {
    id: "business-pricing-signal",
    title: "Find the signal in a pricing page",
    summary: "Learn what tiers, guarantees, and limits reveal about a company's customer strategy.",
    interests: ["Business", "Entrepreneurship"],
    format: "brief",
    durationMinutes: 6,
    level: "starter",
    createdAt: "2026-06-18T08:00:00.000Z",
    sourceLabel: "Business models",
    media: { kind: "text", status: "available" },
  },
  {
    id: "business-weekly-review",
    title: "A weekly business review you can finish in 20 minutes",
    summary: "Track pipeline, customer learning, bottlenecks, and next bets without creating a reporting ritual.",
    interests: ["Business", "Entrepreneurship"],
    format: "article",
    durationMinutes: 10,
    level: "intermediate",
    createdAt: "2026-06-17T08:00:00.000Z",
    sourceLabel: "Operating cadence",
    media: { kind: "text", status: "available" },
  },
  {
    id: "finance-cash-buffer",
    title: "Build a cash buffer using a simple runway formula",
    summary: "Estimate monthly burn, risk windows, and savings targets with a lightweight personal finance model.",
    interests: ["Finance"],
    format: "article",
    durationMinutes: 9,
    level: "starter",
    createdAt: "2026-06-16T08:00:00.000Z",
    sourceLabel: "Money habits",
    media: { kind: "text", status: "available" },
  },
  {
    id: "finance-index-funds",
    title: "Why index funds are hard to beat",
    summary: "A concise explanation of diversification, fees, time horizons, and compounding.",
    interests: ["Finance", "Business"],
    format: "video",
    durationMinutes: 11,
    level: "starter",
    createdAt: "2026-06-15T08:00:00.000Z",
    sourceLabel: "Investing basics",
    media: { kind: "video", status: "planned" },
  },
  {
    id: "fitness-zone-two",
    title: "Zone 2 training without overthinking it",
    summary: "Use conversation pace, weekly volume, and recovery signals to build cardio capacity.",
    interests: ["Fitness"],
    format: "brief",
    durationMinutes: 5,
    level: "starter",
    createdAt: "2026-06-14T08:00:00.000Z",
    sourceLabel: "Training",
    media: { kind: "video", status: "planned" },
  },
  {
    id: "fitness-strength-template",
    title: "A three-day strength template for busy weeks",
    summary: "Compound movements, progression, and minimum-effective volume arranged for consistency.",
    interests: ["Fitness"],
    format: "challenge",
    durationMinutes: 14,
    level: "intermediate",
    createdAt: "2026-06-13T08:00:00.000Z",
    sourceLabel: "Strength plan",
    media: { kind: "text", status: "available" },
  },
  {
    id: "science-evidence-levels",
    title: "Read scientific claims by evidence level",
    summary: "Separate anecdotes, observational studies, randomized trials, and meta-analyses before sharing a claim.",
    interests: ["Science"],
    format: "article",
    durationMinutes: 9,
    level: "starter",
    createdAt: "2026-06-12T08:00:00.000Z",
    sourceLabel: "Scientific literacy",
    media: { kind: "text", status: "available" },
  },
  {
    id: "science-space-weather",
    title: "What space weather does to technology on Earth",
    summary: "Solar flares, magnetic storms, satellites, and power grids explained as one connected system.",
    interests: ["Science", "Technology"],
    format: "video",
    durationMinutes: 13,
    level: "intermediate",
    createdAt: "2026-06-11T08:00:00.000Z",
    sourceLabel: "Space systems",
    media: { kind: "video", status: "planned" },
  },
  {
    id: "technology-api-contracts",
    title: "Design API contracts that age well",
    summary: "Use versioning, predictable errors, and narrow response shapes to reduce future integration pain.",
    interests: ["Technology"],
    format: "article",
    durationMinutes: 12,
    level: "intermediate",
    createdAt: "2026-06-10T08:00:00.000Z",
    sourceLabel: "Software architecture",
    media: { kind: "text", status: "available" },
  },
  {
    id: "technology-privacy-check",
    title: "A five-minute privacy check for new apps",
    summary: "Review permissions, backups, data export, and notification defaults before you commit your workflow.",
    interests: ["Technology"],
    format: "brief",
    durationMinutes: 5,
    level: "starter",
    createdAt: "2026-06-09T08:00:00.000Z",
    sourceLabel: "Digital hygiene",
    media: { kind: "text", status: "available" },
  },
  {
    id: "fashion-capsule-wardrobe",
    title: "Build a capsule wardrobe around repeatable silhouettes",
    summary: "Choose anchor pieces, color constraints, and styling rules that make daily outfits easier.",
    interests: ["Fashion"],
    format: "article",
    durationMinutes: 8,
    level: "starter",
    createdAt: "2026-06-08T08:00:00.000Z",
    sourceLabel: "Style systems",
    media: { kind: "video", status: "planned" },
  },
  {
    id: "fashion-materials",
    title: "Read clothing quality through fabric and construction",
    summary: "A quick guide to fibers, seams, drape, and care labels before buying.",
    interests: ["Fashion", "Business"],
    format: "brief",
    durationMinutes: 7,
    level: "starter",
    createdAt: "2026-06-07T08:00:00.000Z",
    sourceLabel: "Buying better",
    media: { kind: "text", status: "available" },
  },
  {
    id: "music-active-listening",
    title: "Active listening: hear arrangement before lyrics",
    summary: "Train your ear to notice rhythm, texture, dynamics, and production choices in one pass.",
    interests: ["Music"],
    format: "audio",
    durationMinutes: 10,
    level: "starter",
    createdAt: "2026-06-06T08:00:00.000Z",
    sourceLabel: "Listening practice",
    media: { kind: "audio", status: "available" },
  },
  {
    id: "music-practice-loop",
    title: "Use 12-minute loops to practice an instrument",
    summary: "Break warmup, focus reps, tempo work, and review into a session that is easy to repeat.",
    interests: ["Music", "Fitness"],
    format: "challenge",
    durationMinutes: 12,
    level: "intermediate",
    createdAt: "2026-06-05T08:00:00.000Z",
    sourceLabel: "Practice design",
    media: { kind: "video", status: "planned" },
  },
  {
    id: "entrepreneurship-customer-calls",
    title: "Ask better questions in customer calls",
    summary: "Move from opinions to past behavior, costs, workarounds, and buying triggers.",
    interests: ["Entrepreneurship", "Business"],
    format: "article",
    durationMinutes: 11,
    level: "starter",
    createdAt: "2026-06-04T08:00:00.000Z",
    sourceLabel: "Customer discovery",
    media: { kind: "text", status: "available" },
  },
  {
    id: "entrepreneurship-launch-scope",
    title: "Cut launch scope without cutting the promise",
    summary: "Identify the smallest useful outcome, remove ornamental work, and ship a sharper first version.",
    interests: ["Entrepreneurship", "Technology"],
    format: "challenge",
    durationMinutes: 15,
    level: "intermediate",
    createdAt: "2026-06-03T08:00:00.000Z",
    sourceLabel: "Launch strategy",
    media: { kind: "video", status: "planned" },
  },
  {
    id: "other-learning-map",
    title: "Map any new topic before you dive in",
    summary: "List the vocabulary, core debates, trusted sources, and first project for an unfamiliar field.",
    interests: ["Other"],
    format: "brief",
    durationMinutes: 6,
    level: "starter",
    createdAt: "2026-06-02T08:00:00.000Z",
    sourceLabel: "Learning method",
    media: { kind: "text", status: "available" },
  },
  {
    id: "other-note-review",
    title: "Turn saved notes into next actions",
    summary: "A short review ritual for converting interesting ideas into practice, projects, or questions.",
    interests: ["Other", "Business"],
    format: "article",
    durationMinutes: 8,
    level: "starter",
    createdAt: "2026-06-01T08:00:00.000Z",
    sourceLabel: "Knowledge workflow",
    media: { kind: "text", status: "available" },
  },
];

function formatToPostContentType(format: LearningContent["format"]): Post["content_type"] {
  if (format === "audio") {
    return "podcast";
  }

  if (format === "brief" || format === "challenge") {
    return "thread";
  }

  return format;
}

export const fallbackFeedItems: FeedItem[] = learningContent.map((content, index) => ({
  id: content.id,
  author_id: localProfiles[0].id,
  title: content.title,
  summary: content.summary,
  url: null,
  content_type: formatToPostContentType(content.format),
  topics: content.interests,
  difficulty: content.level === "deep" ? "advanced" : content.level === "intermediate" ? "intermediate" : "beginner",
  estimated_minutes: content.durationMinutes,
  relevance: Math.max(70, 98 - index),
  created_at: content.createdAt,
  profile: {
    username: localProfiles[0].username,
    full_name: localProfiles[0].full_name,
    avatar_url: localProfiles[0].avatar_url,
    headline: localProfiles[0].headline,
  },
}));

export const emptyPostDraft: Pick<
  Post,
  "title" | "summary" | "url" | "content_type" | "topics" | "difficulty" | "estimated_minutes"
> = {
  title: "",
  summary: "",
  url: "",
  content_type: "article",
  topics: [],
  difficulty: "beginner",
  estimated_minutes: 10,
};
